cxx_library(
  name = 'scripthelper',
  header_namespace = '',
  exported_headers = [
    'scripthelper.h',
  ],
  srcs = [
    'scripthelper.cpp',
  ],
  visibility = [
    '//...'
  ],
  deps = [
    '//:angelscript',
  ],
)
